# inspired by https://github.com/PrefectHQ/cicd-example-workspaces/blob/72b4eb46598596f70335d90ce88d47365736a6dc/.github/workflows/project-1-deploy.yaml

name: Deploy Prefect flow
env:
  PROJECT_NAME: prefect-3-demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
      name: Deploy to production
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      env:
        ENVIRONMENT: prod

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Get commit hash
          id: get-commit-hash
          run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

        - name: Build and push
          id: build-docker-image
          env:
              GITHUB_SHA: ${{ steps.get-commit-hash.outputs.COMMIT_HASH }}
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: entreecapital/${{env.PROJECT_NAME}}:${{ env.GITHUB_SHA }}
            cache-from: type=gha
            cache-to: type=gha,mode=max

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
            cache: "pip"
        - run: pip install -r requirements.txt

        - name: Prefect Auth
          run: |
                prefect cloud login \
                --key ${{ secrets.PREFECT_API_KEY }} \
                --workspace entree-chef/default
          shell: bash

        - name: Prefect Deploy
          env:
            PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
            IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ steps.get-commit-hash.outputs.COMMIT_HASH }}-${{ env.ENVIRONMENT }}
          run: |
            prefect cloud workspace ls  
            prefect deploy --all --prefect-file prefect.yaml